### ISSUE TITLE
Support django rest framework v3

### ISSUE THREAD

**Issue by Ian-Foote** [Ian-Foote/rest-framework-generic-relations#12]
Django rest framework v3 is the future.

**Comment by jessemorton** [comment]
+1 Any update on this, or expected timeline?

**Comment by emptyflash** [comment]
+1 as well, it seems like the PR that's in for it has halted. I've tried taking a look at it myself, but I don't have enough familiarity with DRF's innards to make much sense of it.

**Comment by wimglenn** [comment]
+1

**Comment by Ian-Foote** [comment]
Fixed by #15.
