### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by Ian-Foote** [Ian-Foote/rest-framework-generic-relations#13]
Before [upgrading to DRF v3](https://github.com/Ian-Foote/rest-framework-generic-relations/issues/12), a final version that supports DRF v2 should be released.

**Comment by Ian-Foote** [comment]
@smcoll Are there any outstanding issues/pull requests you think should be resolved before I make this release?

**Comment by smcoll** [comment]
Not unless you're interested in #9.  i'm happy to change the implementation as well, if you have thoughts on it.
