### ISSUE TITLE
`determine_[de]serializer_for_data` is confusingly named

### ISSUE THREAD

**Issue by craigds** [Ian-Foote/rest-framework-generic-relations#16]
Terminology in GenericField:
“deserializer” —> a thing that turns your model into a json blob
“serializer” —> a thing that turns your json blob into a model

These seem backward to me. I don't know exactly what the fix should be. Merely switching them could be a bit of a confusing upgrade path.

What about renaming them at the same time? `determine` could be shortened to `get`. Then we could leave fallbacks in place for the old names, with deprecation warnings.

Perhaps for extra clarity, 'data' on the outgoing serializer could be 'instance', signalling that you're serializing a model instance.

* `determine_deserializer_for_data` -> `get_serializer_for_instance`
* `determine_serializer_for_data` -> `get_deserializer_for_data`

Another alternative:
* `determine_deserializer_for_data` -> `get_outgoing_serializer`
* `determine_serializer_for_data` -> `get_incoming_serializer`

**Comment by craigds** [comment]
Sorry I submitted this _after_ 1.0 ;) I just noticed it actually.

**Comment by craigds** [comment]
Happy to do this and submit a PR btw, if you'd be okay with this in principle

**Comment by Ian-Foote** [comment]
Good spot. I think I like `serializer_for_instance` and `deserializer_for_data` best, but it can be bikeshedded on the PR.
