### ISSUE TITLE
GenericModelSerializer

### ISSUE THREAD

**Issue by craigds** [Ian-Foote/rest-framework-generic-relations#21]
We've been using this internally for a while, but since I'm on a roll today I'll pitch it to you.

Suppose you want to serialize a list of top-level items, and they're not all the same:

```
GET /items/
[
{ "type": "book", "title": "To Kill a Mockingbird", "author": "Harper Lee" },
{ "type": "dvd", "title": "Die Hard", "rating": 5 }
]
```

We do this using a serializer that delegates to different registered serializers for each type of item.

The code is actually identical to `GenericRelatedField`, but subclassing `Serializer` instead of `Field`: https://github.com/craigds/rest-framework-generic-relations/commit/ec93ae6f6af83fa945404e8843f01fa6f879ba57

Is this something you'd include? If so I'll clean it up and PR it.

**Comment by Ian-Foote** [comment]
Looks good to me.
