### ISSUE TITLE
Could not determine a valid serializer for value

### ISSUE THREAD

**Issue by rawbeans** [Ian-Foote/rest-framework-generic-relations#26]
I am trying to use the HyperlinkedRelatedField to write to my GenericRelatedField

However I am getting the following error:

`"Could not determine a valid serializer for value u'/api/users/1/'."`

Looking at the codebase, it is iterating through all available serializers until it finds one that works. Where do I add serializers to this list? Does it have to be done manually?

**Comment by Ian-Foote** [comment]
The [readme]() has this example:

```python
class TagSerializer(serializers.ModelSerializer):
    """
    A `Tag` serializer with a `GenericRelatedField` mapping all possible
    models to properly set up `HyperlinkedRelatedField`s.
    """
    tagged_object = serializers.GenericRelatedField({
        Bookmark: serializers.HyperlinkedRelatedField(
            queryset = Bookmark.objects.all(),
            view_name='bookmark-detail',
        ),
        Note: serializers.HyperlinkedRelatedField(
            queryset = Note.objects.all(),
            view_name='note-detail',
        ),
    })

    class Meta:
        model = TaggedItem
        fields = ('tag_name', 'tagged_object')
```

Does this help? If not, can you show me your code (or a minimal example)?

**Comment by rawbeans** [comment]
Found the issue. I was not providing the full view_name as mine were in a separate namespace. Fixed by changing to: 

`view_name='<namespace>:<view_name>`
