### ISSUE TITLE
Null value for Generic Relation causes Invalid Model Error

### ISSUE THREAD

**Issue by turukawa** [Ian-Foote/rest-framework-generic-relations#3]
I have a number of GenericForeignKey relations on my model and they are all permitted to be nulls.

I find that `determine_deserializer_for_data` throws an error when trying to figure out the class for the specific value when it is null. This can be fixed (hopefully without causing issues elsewhere) as follows by adding a quick `if`:

    def field_to_native(self, obj, field_name):
        """
        Delegates to the `to_native` method of the serializer registered
        under obj.__class__
        """
        value = super(GenericRelatedField, self).field_to_native(
            obj, field_name)
        if value:
            serializer = self.determine_deserializer_for_data(value)
    
            # Necessary because of context, field resolving etc.
            serializer.initialize(self.parent, field_name)
            return serializer.to_native(value)

**Comment by Ian-Foote** [comment]
Sorry for the very late reply. If anyone still needs this, feel free to put it in a pull request.
