### ISSUE TITLE
Support DRF > 3.9

### ISSUE THREAD

**Issue by uiboy** [Ian-Foote/rest-framework-generic-relations#45]
Please update to support Django rest framework > 3.9 to avoid security issues. We are unable to upgrade DRF as a consequence. 

There are moderate severity vulnerabilities in django rest framework < 3.9 on which `rest-framework-generic-relations` depends. 
Info: 
WS-2019-0037 
moderate severity
Vulnerable versions: < 3.9.1
Patched version: 3.9.1
Django-Rest-Framework, before 3.9.1, has a XSS vulnerability caused by disabled autoescaping in the default DRF Browsable API view templates.

Fixed here in DRF https://github.com/encode/django-rest-framework/commit/75a489150ae24c2f3c794104a8e98fa43e2c9ce9

**Comment by Ian-Foote** [comment]
Fixed in #44
