### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by elcolie** [Ian-Foote/rest-framework-generic-relations#49]
How can I solve this `ImportError: cannot import name 'six' from 'django.utils'` in Django3?

**Comment by elcolie** [comment]
They are 2 files. `relations.py` and `serializers.py`
Change from the old one from `django.utils.six` to `import six`
Hope official decision will be made soon. Since I don't want to maintain my own fork

https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils

**Comment by elcolie** [comment]
Temporal use with [Django3](https://github.com/elcolie/rest-framework-generic-relations)

**Comment by craigds** [comment]
v2.0.0 has been released, solves this problem.
