### ISSUE TITLE
django-rest-framework 2.4.x support

### ISSUE THREAD

**Issue by steveed** [Ian-Foote/rest-framework-generic-relations#5]
relations.py is importing six from rest_framework and as of 2.4.0 rest_framework appears to have removed six.py from their source.

**Comment by smcoll** [comment]
Appears to be a fix here: https://github.com/jayfk/rest-framework-generic-relations/commit/d5d9b06be7fa4e9e071fc54ded3ce436539c75c0

**Comment by steveed** [comment]
I put in a pull request a while back that includes fixes to the tests #6

**Comment by smcoll** [comment]
@steveed you're right; i'll close mine.

**Comment by Ian-Foote** [comment]
Thanks for reminding me about this.
