### ISSUE TITLE
Issues when upgrading rest framework to 3.11

### ISSUE THREAD

**Issue by hvdklauw** [Ian-Foote/rest-framework-generic-relations#50]
I run into issues when I try to upgrade to rest framework 3.11.

My package resolver (poetry) will install 1.2.1 with 3.11 (because the version restriction there is `>=3.0.0<4`) but that imports six from rest framework which isn't there anymore.
1.2.2 might work, but the version restriction there is `>=3.0.0,<3.11` so that won't actually work.

Please release a new version that supports DRF 3.11 (I think just loosening the restriction in setup.py would be enough)

**Comment by hvdklauw** [comment]
Thanks for merging a fix, can we get a release too?

**Comment by craigds** [comment]
I don't have access to the pypi project, @Ian-Foote will need to do the release. Or add me to the pypi project and I can do it 😄

**Comment by Ian-Foote** [comment]
@craigds What is your pypi account? I've been meaning to get around to this, but life's been too busy the past few months.

**Comment by craigds** [comment]
My pypi username is craigds too :)

**Comment by craigds** [comment]
v2.0.0 has been released :)
