### ISSUE TITLE
rest-framework-generic-relations is not compatible with Django 3.0

### ISSUE THREAD

**Issue by Torogavrus** [Ian-Foote/rest-framework-generic-relations#52]
Django 3.0 drops support for Python 2, causing issues like this:
`
File "/Folder/Project/nodule/api/serializers/.py", line 1, in <module>
    from generic_relations.relations import GenericRelatedField
  File "/Folder/project_venv_d3/lib/python3.6/site-packages/generic_relations/relations.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
`

There's a full list of these python 2 compatibility APIs in the [Django 3.0 release notes.](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis)

**Comment by craigds** [comment]
already in master, just needs a release. done in #51

**Comment by craigds** [comment]
v2.0.0 has been released, solves this problem.
